[workspace]
members = ["firmware"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.75.0"
authors = ["Boris Faure <boris@fau.re>"]


[profile.release]
opt-level = 'z'
lto = true
incremental = false
